#!/usr/bin/env bash
# Prints Sources/Pumlpad/Keywords.swift built from `plantuml --list-keywords`.
set -euo pipefail

plantuml="${PLANTUML:-plantuml}"
version="$("$plantuml" --version 2>/dev/null | head -1)"

"$plantuml" --list-keywords 2>/dev/null | awk -v version="$version" '
  /^;EOF/ { exit }
  /^;[0-9]+$/ { next }
  /^;/ { section = substr($0, 2); next }
  NF {
    gsub(/\\/, "\\\\"); gsub(/"/, "\\\"")
    count[section]++
    words[section, count[section]] = "\"" $0 "\""
  }
  function emit(section, name,   i, line) {
    printf "    static let %s: [String] = [\n", name
    line = "       "
    for (i = 1; i <= count[section]; i++) {
      if (length(line) + length(words[section, i]) > 110) { print line; line = "       " }
      line = line " " words[section, i] ","
    }
    if (line != "       ") print line
    print "    ]"
  }
  END {
    print "// Generated by scripts/gen-keywords.sh from `plantuml --list-keywords`. Do not edit."
    print "// " version
    print ""
    print "enum Keywords {"
    emit("type", "types"); print ""
    emit("keyword", "keywords"); print ""
    emit("preprocessor", "preprocessor"); print ""
    emit("skinparameter", "skinParameters"); print ""
    emit("color", "colors")
    print "}"
  }
'
